apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: cas-container
  name: cas-container
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
