apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cassandra
  name: cassandra
spec:
  ports:
  - name: "7000"
    port: 7000
    targetPort: 7000
  - name: "7199"
    port: 7199
    targetPort: 7199
  - name: "9042"
    port: 9042
    targetPort: 9042
  selector:
    io.kompose.service: cassandra
status:
  loadBalancer: {}
