apiVersion: apps/v1
kind: Deployment
metadata:
  name: controllerdataprovider-depl
spec:
  selector:
    matchLabels:
      io.kompose.service: controllerdataprovider
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: controllerdataprovider
    spec:
      containers:
        - name: controllerdataprovider
          image: "$(IMAGE_REPOSITORY)/controllerdataprovider:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8452
          volumeMounts:
            - name: mongo-user
              mountPath: /run/secrets/mongo-user
              subPath: mongo-user
            - name: mongo-user-passwd
              mountPath: /run/secrets/mongo-user-passwd
              subPath: mongo-user-passwd
            - name: cassandra-username
              mountPath: /run/secrets/cassandra-username
              subPath: cassandra-username
            - name: cassandra-password
              mountPath: /run/secrets/cassandra-password
              subPath: cassandra-password
            - name: shutdown-secret
              mountPath: /run/secrets/shutdown-secret
              subPath: shutdown-secret
          env:
            - name: IMAGE_REPOSITORY
              valueFrom:
                configMapKeyRef:
                  key: IMAGE_REPOSITORY
                  name: ihotraco-configmap
            - name: SPRING_DATA_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATA_MONGODB_HOST
                  name: ihotraco-configmap
            - name: CASSANDRA_PORT
              valueFrom:
                configMapKeyRef:
                  key: CASSANDRA_PORT
                  name: ihotraco-configmap
            - name: target_url
              valueFrom:
                configMapKeyRef:
                  name: ihotraco-configmap
                  key: target_url
            - name: SERVER_URL
              value: "https://$(target_url)"
            - name: CASSANDRA_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: CASSANDRA_HOSTNAME
                  name: ihotraco-configmap
            - name: java_profiles
              valueFrom:
                configMapKeyRef:
                  name: ihotraco-configmap
                  key: java_profiles
            - name: SPRING_PROFILES_ACTIVE
              value: "$(java_profiles)"
          resources: 
            limits:
              cpu: 200m
              memory: 500Mi
            requests: 
              cpu: 100m
              memory: 400Mi
      volumes:
        - name: mongo-user
          secret:
            secretName: mongo-user
        - name: mongo-user-passwd
          secret:
            secretName: mongo-user-passwd
        - name: cassandra-username
          secret:
            secretName: cassandra-username
        - name: cassandra-password
          secret:
            secretName: cassandra-password
        - name: shutdown-secret
          secret:
            secretName: shutdown-secret
      imagePullSecrets:
      - name: nexus-secrets
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
status: {}
