apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: controllerdataprovider
  name: controllerdataprovider-depl
spec:
  ports:
  - name: "8452"
    port: 8452
    targetPort: 8452
  selector:
    io.kompose.service: controllerdataprovider
  type: ClusterIP
status:
  loadBalancer: {}
