apiVersion: v1
kind: Service
metadata:
  name: devicegateway-depl
spec:
  ports:
  - name: "8449"
    port: 8449
    targetPort: 8449
  - name: "8450"
    port: 8450
    targetPort: 8450
  selector:
    io.kompose.service: devicegateway
  type: ClusterIP
status:
  loadBalancer: {}