apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: identitymanager
  name: identitymanager-depl
spec:
  ports:
  - name: "8451"
    port: 8451
    targetPort: 8451
  selector:
    io.kompose.service: identitymanager
  type: ClusterIP
status:
  loadBalancer: {}
