apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-depl
spec:
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0.9-jammy
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data-container-volume-claim
            - mountPath: /docker-entrypoint-initdb.d/init-mongo.sh
              name: mongo-claim1
          env:
            - name: SPRING_DATA_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATA_MONGODB_HOST
                  name: ihotraco-configmap
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: ihotraco-configmap
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_DATABASE
                  name: ihotraco-configmap
            - name: MONGO_INITDB_ROOT_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: mongo-initdb-root-password-file
                  key: mongo-root-passwd
            - name: MONGO_INITDB_USERNAME 
              valueFrom:
                secretKeyRef:
                  name: mongo-initdb-username-file
                  key: mongo-user
            - name: MONGO_INITDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-initdb-password-file
                  key: mongo-user-passwd
          resources: {}
      restartPolicy: Always
      volumes:
        - name: mongodb-data-container-volume-claim
          persistentVolumeClaim:
            claimName: mongodb-data-container-volume-claim
        - name: mongo-claim1
          persistentVolumeClaim:
            claimName: mongo-claim1
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
status: {}
