apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-claim1-volume
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/mnt/data"
