apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: remoteconnector-depl
spec: 
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment 
    name: remoteconnector-depl
  minReplicas: 3
  maxReplicas: 10 
  behavior: 
    scaleUp: 
      policies: 
      - type: Pods 
        value: 1 
        periodSeconds: 20 
    scaleDown: 
      policies: 
      - type: Percent 
        value: 20
        periodSeconds: 20
  metrics: 
  - type: Resource
    resource: 
      name: cpu
      target: 
        type: Utilization 
        averageUtilization: 80
  - type: Resource 
    resource: 
      name: memory 
      target: 
        type: Utilization 
        averageUtilization: 80
