apiVersion: apps/v1
kind: Deployment
metadata:
  name: remoteconnector-depl
spec:
  selector:
    matchLabels:
      io.kompose.service: remoteconnector
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: remoteconnector
    spec:
      containers:
        - name: remoteconnector
          image: "$(IMAGE_REPOSITORY)/remoteconnector:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8453
          volumeMounts:
            - name: mongo-user
              mountPath: /run/secrets/mongo-user
              subPath: mongo-user
            - name: mongo-user-passwd
              mountPath: /run/secrets/mongo-user-passwd
              subPath: mongo-user-passwd
            - name: shutdown-secret
              mountPath: /run/secrets/shutdown-secret
              subPath: shutdown-secret
            - name: remote-connector-mqtt
              mountPath: /run/secrets/remote-connector-mqtt
              subPath: remote-connector-mqtt
          env:
            - name: IMAGE_REPOSITORY
              valueFrom:
                configMapKeyRef:
                  key: IMAGE_REPOSITORY
                  name: ihotraco-configmap
            - name: SPRING_DATA_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATA_MONGODB_HOST
                  name: ihotraco-configmap
            - name: target_url
              valueFrom:
                configMapKeyRef:
                  name: ihotraco-configmap
                  key: target_url
            - name: SERVER_URL
              value: "https://$(target_url)"
            - name: java_profiles
              valueFrom:
                configMapKeyRef:
                  name: ihotraco-configmap
                  key: java_profiles
            - name: SPRING_PROFILES_ACTIVE
              value: "$(java_profiles)"
            - name: MQTT_SERVER_HOSTNAME
              value: mqtt
          resources: 
            limits:
              cpu: 200m
              memory: 500Mi
            requests: 
              cpu: 100m
              memory: 400Mi
      imagePullSecrets:
        - name: nexus-secrets
      restartPolicy: Always
      volumes:
        - name: mongo-user
          secret:
            secretName: mongo-user
        - name: mongo-user-passwd
          secret:
            secretName: mongo-user-passwd
        - name: shutdown-secret
          secret:
            secretName: shutdown-secret
        - name: remote-connector-mqtt
          secret:
            secretName: remote-connector-mqtt
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
status: {}
