apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: swagger
  name: swagger
spec:
  ports:
  - name: "8455"
    port: 8455
    targetPort: 8080
  selector:
    io.kompose.service: swagger
status:
  loadBalancer: {}
