apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-depl
spec:
  selector:
    matchLabels:
      io.kompose.service: swagger
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: swagger
    spec:
      containers:
      - env:
        - name: PERSIST_AUTHORIZATION
          value: "true"
        - name: URLS
          valueFrom:
            configMapKeyRef:
              key: URLS
              name: ihotraco-configmap
        image: swaggerapi/swagger-ui:v4.5.2
        name: swagger
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
status: {}
